-- Generated from assets/catalogue by scripts/seed-catalogue-products.mjs.
-- Product IDs are deterministic and are embedded in the matching image filename.
insert into public.library_items (id, kind, name, cost, category, contents, component_ids, occasions, photo)
values
  ('product-300-ml-bunny-glass-bottle', 'product', '300 ml Bunny Glass Bottle', 0, '', '', '{}', ARRAY['baby_shower'], 'assets/catalogue/300 ml Bunny Glass Bottle--product-300-ml-bunny-glass-bottle.png'),
  ('product-air-tight-container', 'product', 'Air tight container', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Air tight container--product-air-tight-container.png'),
  ('product-antique-floral-mandala-tiffin-box', 'product', 'Antique Floral Mandala Tiffin Box', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Antique Floral Mandala Tiffin Box--product-antique-floral-mandala-tiffin-box.png'),
  ('product-banaras-blouse-material-1m', 'product', 'Banaras Blouse Material 1M', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Banaras Blouse Material 1M--product-banaras-blouse-material-1m.png'),
  ('product-bangle-box', 'product', 'Bangle Box', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Bangle Box--product-bangle-box.png'),
  ('product-black-shaker-bottle-with-blue-flip-cap', 'product', 'Black Shaker Bottle with Blue Flip Cap', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Black Shaker Bottle with Blue Flip Cap--product-black-shaker-bottle-with-blue-flip-cap.png'),
  ('product-brass-dabara-set', 'product', 'Brass Dabara Set', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Brass Dabara Set--product-brass-dabara-set.png'),
  ('product-canister', 'product', 'Canister', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Canister--product-canister.png'),
  ('product-character-glass-bottle', 'product', 'Character Glass Bottle', 0, '', '', '{}', ARRAY['baby_shower'], 'assets/catalogue/Character Glass Bottle--product-character-glass-bottle.png'),
  ('product-coffee-mug', 'product', 'Coffee Mug', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Coffee Mug--product-coffee-mug.png'),
  ('product-colorful-mandala-tin', 'product', 'Colorful Mandala Tin', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Colorful Mandala Tin--product-colorful-mandala-tin.png'),
  ('product-cozy-woven-jute-tote-with-lace-trim', 'product', 'Cozy Woven Jute Tote with Lace Trim', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Cozy Woven Jute Tote with Lace Trim--product-cozy-woven-jute-tote-with-lace-trim.png'),
  ('product-decorative-kumkum-and-turmeric-vials', 'product', 'Decorative Kumkum and Turmeric Vials', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Decorative Kumkum and Turmeric Vials--product-decorative-kumkum-and-turmeric-vials.png'),
  ('product-designer-tray', 'product', 'Designer Tray', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Designer Tray--product-designer-tray.png'),
  ('product-embossed-folk-art-keepsake-box', 'product', 'Embossed Folk Art Keepsake Box', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Embossed Folk Art Keepsake Box--product-embossed-folk-art-keepsake-box.png'),
  ('product-enamel-bangles-set-of-3', 'product', 'Enamel Bangles (Set of 3)', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Enamel Bangles (Set of 3)--product-enamel-bangles-set-of-3.png'),
  ('product-engraved-jewel-box', 'product', 'Engraved Jewel Box', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Engraved Jewel Box--product-engraved-jewel-box.png'),
  ('product-engraved-tiffin-box', 'product', 'Engraved Tiffin Box', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Engraved Tiffin Box--product-engraved-tiffin-box.png'),
  ('product-engraved-tree-stainless-steel-plate', 'product', 'Engraved Tree Stainless Steel Plate', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Engraved Tree Stainless Steel Plate--product-engraved-tree-stainless-steel-plate.png'),
  ('product-fancy-glass-bottle', 'product', 'Fancy Glass Bottle', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Fancy Glass Bottle--product-fancy-glass-bottle.png'),
  ('product-fancy-pencil', 'product', 'Fancy Pencil', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Fancy Pencil--product-fancy-pencil.png'),
  ('product-fancy-stationary-pencil', 'product', 'Fancy Stationary Pencil', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Fancy Stationary Pencil--product-fancy-stationary-pencil.png'),
  ('product-fancy-water-bottle', 'product', 'Fancy Water Bottle', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Fancy Water Bottle--product-fancy-water-bottle.png'),
  ('product-floral-turquoise-tin', 'product', 'Floral Turquoise Tin', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Floral Turquoise Tin--product-floral-turquoise-tin.png'),
  ('product-flower-hair-band', 'product', 'Flower Hair Band', 0, '', '', '{}', ARRAY['baby_shower'], 'assets/catalogue/Flower Hair Band--product-flower-hair-band.png'),
  ('product-fully-insulated-bottle', 'product', 'Fully Insulated Bottle', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Fully Insulated Bottle--product-fully-insulated-bottle.png'),
  ('product-german-silver-floral-embossed-metal-tray', 'product', 'German Silver Floral Embossed Metal Tray', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/German Silver Floral Embossed Metal Tray--product-german-silver-floral-embossed-metal-tray.png'),
  ('product-german-silver-miniature-ornament-thulasi-maadam-02', 'product', 'German Silver Miniature Ornament _ Thulasi Maadam 02', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/German Silver Miniature Ornament _ Thulasi Maadam 02--product-german-silver-miniature-ornament-thulasi-maadam-02.png'),
  ('product-german-silver-miniature-ornament-thulasi-maadam', 'product', 'German Silver Miniature Ornament _ Thulasi Maadam', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/German Silver Miniature Ornament _ Thulasi Maadam--product-german-silver-miniature-ornament-thulasi-maadam.png'),
  ('product-german-silver-ornate-with-red-velvet-box', 'product', 'German Silver Ornate with Red Velvet Box', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/German Silver Ornate with Red Velvet Box--product-german-silver-ornate-with-red-velvet-box.png'),
  ('product-gift-box', 'product', 'Gift box', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Gift box--product-gift-box.png'),
  ('product-glass-tumbler-with-leather-sleeve', 'product', 'Glass Tumbler With Leather Sleeve', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Glass Tumbler With Leather Sleeve--product-glass-tumbler-with-leather-sleeve.png'),
  ('product-golden-devotional-plaques-display', 'product', 'Golden Devotional Plaques Display', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Golden Devotional Plaques Display--product-golden-devotional-plaques-display.png'),
  ('product-gomadha-fridge-magnet', 'product', 'Gomadha Fridge Magnet', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Gomadha Fridge Magnet--product-gomadha-fridge-magnet.png'),
  ('product-hammered-copper-box-with-floral-lid', 'product', 'Hammered Copper Box with Floral Lid', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Hammered Copper Box with Floral Lid--product-hammered-copper-box-with-floral-lid.png'),
  ('product-hammered-jars', 'product', 'Hammered Jars', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Hammered Jars--product-hammered-jars.png'),
  ('product-insulated-canister', 'product', 'Insulated Canister', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Insulated Canister--product-insulated-canister.png'),
  ('product-insulated-lunch-box', 'product', 'Insulated Lunch Box', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Insulated Lunch Box--product-insulated-lunch-box.png'),
  ('product-insulated-small-lunchbox', 'product', 'Insulated Small Lunchbox', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Insulated Small Lunchbox--product-insulated-small-lunchbox.png'),
  ('product-jasmine-flower-hair-band-01', 'product', 'Jasmine Flower Hair Band 01', 0, '', '', '{}', ARRAY['baby_shower'], 'assets/catalogue/Jasmine Flower Hair Band 01--product-jasmine-flower-hair-band-01.png'),
  ('product-jasmine-flower-hair-band-02', 'product', 'Jasmine Flower Hair Band 02', 0, '', '', '{}', ARRAY['baby_shower'], 'assets/catalogue/Jasmine Flower Hair Band 02--product-jasmine-flower-hair-band-02.png'),
  ('product-jute-bag-01', 'product', 'Jute Bag 01', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Jute Bag 01--product-jute-bag-01.png'),
  ('product-jute-bag-02', 'product', 'Jute Bag 02', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Jute Bag 02--product-jute-bag-02.png'),
  ('product-jute-bag-03', 'product', 'Jute Bag 03', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Jute Bag 03--product-jute-bag-03.png'),
  ('product-jute-bag-04', 'product', 'Jute Bag 04', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Jute Bag 04--product-jute-bag-04.png'),
  ('product-kumkum-manjal-and-thali-kayiru', 'product', 'Kumkum, Manjal and Thali Kayiru', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Kumkum, Manjal and Thali Kayiru--product-kumkum-manjal-and-thali-kayiru.png'),
  ('product-lime-green-glass-bottle', 'product', 'Lime Green Glass Bottle', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Lime Green Glass Bottle--product-lime-green-glass-bottle.png'),
  ('product-love-s-beauty-heart-tin', 'product', 'Love’s Beauty Heart Tin', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Love’s Beauty Heart Tin--product-love-s-beauty-heart-tin.png'),
  ('product-mason-jar', 'product', 'Mason Jar', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Mason Jar--product-mason-jar.png'),
  ('product-mini-german-silver-cup', 'product', 'Mini German Silver Cup', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Mini German Silver Cup--product-mini-german-silver-cup.png'),
  ('product-noice-water-bottle', 'product', 'Noice Water Bottle', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Noice Water Bottle--product-noice-water-bottle.png'),
  ('product-oil-spray-can', 'product', 'Oil Spray Can', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Oil Spray Can--product-oil-spray-can.png'),
  ('product-oil-spray', 'product', 'Oil Spray', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Oil Spray--product-oil-spray.png'),
  ('product-ornate-black-and-gold-trinket-box', 'product', 'Ornate Black and Gold Trinket Box', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Ornate Black and Gold Trinket Box--product-ornate-black-and-gold-trinket-box.png'),
  ('product-ornate-brass-cow-and-lotus-tray', 'product', 'Ornate Brass Cow and Lotus Tray', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Ornate Brass Cow and Lotus Tray--product-ornate-brass-cow-and-lotus-tray.png'),
  ('product-ornate-decorative-kumkum-box', 'product', 'Ornate Decorative Kumkum Box', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Ornate Decorative Kumkum Box--product-ornate-decorative-kumkum-box.png'),
  ('product-ornate-peacock-brass-diya-thali-set', 'product', 'Ornate Peacock Brass Diya Thali Set', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Ornate Peacock Brass Diya Thali Set--product-ornate-peacock-brass-diya-thali-set.png'),
  ('product-ornate-pichavari-jar', 'product', 'Ornate Pichavari Jar', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Ornate Pichavari Jar--product-ornate-pichavari-jar.png'),
  ('product-piggy-bank', 'product', 'Piggy Bank', 0, '', '', '{}', ARRAY['baby_shower'], 'assets/catalogue/Piggy Bank--product-piggy-bank.png'),
  ('product-potli-bag-01', 'product', 'Potli Bag 01', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Potli Bag 01--product-potli-bag-01.png'),
  ('product-potli-bag-02', 'product', 'Potli Bag 02', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Potli Bag 02--product-potli-bag-02.png'),
  ('product-premium-hammered-gold-canisters', 'product', 'Premium Hammered Gold Canisters', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Premium Hammered Gold Canisters--product-premium-hammered-gold-canisters.png'),
  ('product-premium-spice-jar', 'product', 'Premium Spice Jar', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Premium Spice Jar--product-premium-spice-jar.png'),
  ('product-printed-flask-300ml', 'product', 'Printed Flask 300ml', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Printed Flask 300ml--product-printed-flask-300ml.png'),
  ('product-printed-ss-container', 'product', 'Printed SS Container', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Printed SS Container--product-printed-ss-container.png'),
  ('product-red-velvet-box-with-ornate-german-silver', 'product', 'Red Velvet Box with Ornate German Silver', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Red Velvet Box with Ornate German Silver--product-red-velvet-box-with-ornate-german-silver.png'),
  ('product-scalloped-textured-glass-bowl', 'product', 'Scalloped Textured Glass Bowl', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Scalloped Textured Glass Bowl --product-scalloped-textured-glass-bowl.png'),
  ('product-silk-cotton-blouse-material-1-mt', 'product', 'Silk Cotton Blouse Material 1 Mt', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Silk Cotton Blouse Material 1 Mt--product-silk-cotton-blouse-material-1-mt.png'),
  ('product-silver-ganesha-idol-in-german-silver', 'product', 'Silver Ganesha Idol in German Silver', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Silver Ganesha Idol in German Silver--product-silver-ganesha-idol-in-german-silver.png'),
  ('product-sling-bag-01', 'product', 'Sling Bag 01', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Sling Bag 01--product-sling-bag-01.png'),
  ('product-sling-bag-02', 'product', 'Sling Bag 02', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Sling Bag 02--product-sling-bag-02.png'),
  ('product-sling-bag-03', 'product', 'Sling Bag 03', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Sling Bag 03--product-sling-bag-03.png'),
  ('product-sling-bag-04', 'product', 'Sling Bag 04', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Sling Bag 04--product-sling-bag-04.png'),
  ('product-sling-bag-05', 'product', 'Sling Bag 05', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Sling Bag 05--product-sling-bag-05.png'),
  ('product-sling-bag-06', 'product', 'Sling Bag 06', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Sling Bag 06--product-sling-bag-06.png'),
  ('product-small-basket-with-kumkum-and-turmeric', 'product', 'Small Basket with Kumkum and Turmeric', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Small Basket with Kumkum and Turmeric--product-small-basket-with-kumkum-and-turmeric.png'),
  ('product-small-crystal-glass-jar', 'product', 'Small Crystal Glass Jar', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Small Crystal Glass Jar--product-small-crystal-glass-jar.png'),
  ('product-small-german-silver-ornate-cow-and-calf-serving-tray', 'product', 'Small German Silver Ornate Cow and Calf Serving Tray', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Small German Silver Ornate Cow and Calf Serving Tray--product-small-german-silver-ornate-cow-and-calf-serving-tray.png'),
  ('product-small-jewel-box', 'product', 'Small Jewel Box', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Small Jewel Box--product-small-jewel-box.png'),
  ('product-small-ornate-peacock-brass-trinket-box', 'product', 'Small Ornate Peacock Brass Trinket Box', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Small Ornate Peacock Brass Trinket Box--product-small-ornate-peacock-brass-trinket-box.png'),
  ('product-solid-flask-300ml', 'product', 'Solid Flask 300ml', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Solid Flask 300ml--product-solid-flask-300ml.png'),
  ('product-spice-jar', 'product', 'Spice Jar', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Spice Jar --product-spice-jar.png'),
  ('product-ss-dabara-set', 'product', 'SS Dabara Set', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/SS Dabara Set--product-ss-dabara-set.png'),
  ('product-ss-tiffin-box', 'product', 'SS Tiffin Box', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/SS Tiffin Box--product-ss-tiffin-box.png'),
  ('product-textured-glass-container-with-lid', 'product', 'Textured Glass Container with Lid', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Textured Glass Container with Lid--product-textured-glass-container-with-lid.png'),
  ('product-tray', 'product', 'Tray', 0, '', '', '{}', ARRAY['wedding'], 'assets/catalogue/Tray--product-tray.png'),
  ('product-tropical-pavilion-canister', 'product', 'Tropical Pavilion Canister', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Tropical Pavilion Canister --product-tropical-pavilion-canister.png'),
  ('product-warm-light-organized-love-jar', 'product', 'Warm Light Organized Love Jar', 0, '', '', '{}', ARRAY['all'], 'assets/catalogue/Warm Light Organized Love Jar--product-warm-light-organized-love-jar.png')
on conflict (id) do update set
  name = excluded.name,
  occasions = excluded.occasions,
  photo = excluded.photo,
  updated_at = now();
